export const DEFAULT_OPTIONS = {
  respectValidation: true,
  fillOptionalFields: true, // Default: fill all fields (required + optional)
  locale: 'en_US',
  animationSpeed: 'instant' as const,
};

export const STORAGE_KEYS = {
  OPTIONS: 'formAutoFill_options',
  PROFILES: 'formAutoFill_profiles',
} as const;

export const SUPPORTED_LOCALES = [
  { code: 'en_US', name: 'English (US)', flag: '🇺🇸' },
  { code: 'en_GB', name: 'English (UK)', flag: '🇬🇧' },
  { code: 'en_CA', name: 'English (Canada)', flag: '🇨🇦' },
  { code: 'en_AU', name: 'English (Australia)', flag: '🇦🇺' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸' },
  { code: 'es_MX', name: 'Spanish (Mexico)', flag: '🇲🇽' },
  { code: 'fr', name: 'French', flag: '🇫🇷' },
  { code: 'fr_CA', name: 'French (Canada)', flag: '🇨🇦' },
  { code: 'de', name: 'German', flag: '🇩🇪' },
  { code: 'de_AT', name: 'German (Austria)', flag: '🇦🇹' },
  { code: 'de_CH', name: 'German (Switzerland)', flag: '🇨🇭' },
  { code: 'it', name: 'Italian', flag: '🇮🇹' },
  { code: 'pt_BR', name: 'Portuguese (Brazil)', flag: '🇧🇷' },
  { code: 'pt_PT', name: 'Portuguese (Portugal)', flag: '🇵🇹' },
  { code: 'nl', name: 'Dutch', flag: '🇳🇱' },
  { code: 'pl', name: 'Polish', flag: '🇵🇱' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺' },
  { code: 'tr', name: 'Turkish', flag: '🇹🇷' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷' },
  { code: 'zh_CN', name: 'Chinese (Simplified)', flag: '🇨🇳' },
  { code: 'zh_TW', name: 'Chinese (Traditional)', flag: '🇹🇼' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
  { code: 'sv', name: 'Swedish', flag: '🇸🇪' },
  { code: 'nb_NO', name: 'Norwegian', flag: '🇳🇴' },
  { code: 'da', name: 'Danish', flag: '🇩🇰' },
  { code: 'fi', name: 'Finnish', flag: '🇫🇮' },
  { code: 'cs', name: 'Czech', flag: '🇨🇿' },
  { code: 'el', name: 'Greek', flag: '🇬🇷' },
  { code: 'he', name: 'Hebrew', flag: '🇮🇱' },
  { code: 'id_ID', name: 'Indonesian', flag: '🇮🇩' },
  { code: 'th', name: 'Thai', flag: '🇹🇭' },
  { code: 'vi', name: 'Vietnamese', flag: '🇻🇳' },
  { code: 'ro', name: 'Romanian', flag: '🇷🇴' },
  { code: 'uk', name: 'Ukrainian', flag: '🇺🇦' },
] as const;

export const FIELD_PATTERNS = {
  email: /email|e-mail|correo/i,
  firstName: /first.*name|fname|given.*name|nombre/i,
  lastName: /last.*name|lname|surname|family.*name|apellido/i,
  fullName: /^name$|full.*name|your.*name/i,
  phone: /phone|tel|mobile|celular/i,
  address: /address|street|direccion/i,
  city: /city|ciudad/i,
  state: /state|province|provincia/i,
  zip: /zip|postal|codigo.*postal/i,
  country: /country|pais/i,
  company: /company|organization|empresa/i,
  username: /user.*name|login/i,
  password: /password|passwd|contraseña/i,
  url: /website|url|site/i,
  age: /age|edad/i,
  date: /date|fecha/i,
} as const;
